### PR TITLE
Install net-ssh < 2.10 for ruby < 2.0

### PR DESCRIPTION
**Pull request by biinari**
Fixes [busser issue #32](https://github.com/test-kitchen/busser/issues/32)

### CODE REVIEW

**Comment by jorhett** [comment]
is the build failure due to lack of examples?  Hoping to see this get pushed out...

**Comment by jorhett** [comment]
Confirmed this works. Kitchen fails as shown in the bug report. Using the patch provided here:

 ```
$ kitchen login
(snip)
~$ sudo bash
~# cd /tmp/verifier/gems/gems/busser-serverspec-0.5.7/
/tmp/verifier/gems/gems/busser-serverspec-0.5.7# wget https://github.com/Fatsoma/busser-serverspec/commit/c9172795b1643ee125dd44bfe4b88144c48d886a.patch - | patch -p1
patching file lib/busser/runner_plugin/serverspec.rb
/tmp/verifier/gems/gems/busser-serverspec-0.5.7# exit
~$ exit
logout
Connection to 127.0.0.1 closed.
$ kitchen verify
-----> Starting Kitchen (v1.4.2)
-----> Verifying <default-ubuntu-1204>...
       Preparing files for transfer
-----> Busser installation detected (busser)
       Installing Busser plugins: busser-serverspec
       Plugin serverspec already installed
       Removing /tmp/verifier/suites/serverspec
       Transferring files to <default-ubuntu-1204>
-----> Running serverspec test suite
-----> Installing net-ssh < 2.10
Fetching: net-ssh-2.9.2.gem (100%)
-----> Installing Serverspec..
```

**Comment by biinari** [comment]
The same failure seems to occur on master (though apparently not at time of latest build on travis https://travis-ci.org/test-kitchen/busser-serverspec/builds/60158722).

**Comment by cl-lab-k** [comment]
build failure is long-standing dispute ( #33 ), but i cannot find why it occurs...

**Comment by cl-lab-k** [comment]
maybe root cause is aruba: https://github.com/cucumber/aruba/pull/232

**Comment by jorhett** [comment]
Hey so wandering off on why test builds fail is fine, but the patch works and solves a problem affecting everyone who installs ChefDK today. Can we merge the patch and solve the testing problems in another bug?

**Comment by cl-lab-k** [comment]
ok, i just released v0.6.0 with this pr. thank you for your works!

**Comment by biinari** [comment]
Seems as if the directory `/tmp/busser-serverspec-install*/suites/serverspec/localhost` is not being created correctly

**Comment by biinari** [comment]
Ace, thanks @cl-lab-k. Yes it looks like the directory '/tmp/busser-serverspec-install*/suites/serverspec' is being created ok but not the 'localhost' directory within it for the 'default_spec.rb' to go in.

**Comment by jorhett** [comment]
Any possibility of a 0.5.8?  I think with the version locking in place, this fix won't be used by dependency installers. The entire goal is to fix backwards compatibility.

**Comment by cl-lab-k** [comment]
@biinari 
> not the 'localhost' directory within it for the 'default_spec.rb' to go in.

it goes in `$CWD/tmp/aruba/tmp/busser-serverspec-install/suites/serverspec/localhost/default_spec.rb`.
aruba > 0.6.x maybe cause this problem, but i cannot find how to fix now.

@jorhett 
sorry, i do not understand what you say because of lacking of my English skill.
do you want me to just release v0.5.8 without any changes from v0.6.0? please tell me what do i do.

**Comment by bdeitte** [comment]
I will try to answer for @jorhett here, since I need this fix too.  Yes it would be nice to just release v0.5.8 without any changes.  Thanks.

**Comment by cl-lab-k** [comment]
just released v0.5.8 (without any changes from v0.6.0), thank you for your all suggestions.

**Comment by jorhett** [comment]
Finally got to retest today and it's grabbing v0.5.9 and working. Thank you!

```
Fetching: busser-0.7.1.gem (100%)
       Successfully installed thor-0.19.0
       Successfully installed busser-0.7.1
       2 gems installed
       Installing Busser plugins: busser-serverspec
       Plugin serverspec installed (version 0.5.9)
-----> Running postinstall for serverspec plugin
       Suite path directory /tmp/verifier/suites does not exist, skipping.
       Transferring files to <default-ubuntu-1204>
-----> Running serverspec test suite
-----> Installing net-ssh < 2.10
Fetching: net-ssh-2.9.2.gem (100%)
-----> Installing Serverspec..
```

**Comment by bdeitte** [comment]
I also saw today that this works, thanks.

**Pull request merged**
